version: '3'
services:
  flydrive:
    container_name: flydrive
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - localstack-s3
    env_file:
      - ./.env.testing
    volumes:
      - .:/app
      - /app/node_modules
    command: tail -f /dev/null

  # Based on http://bluesock.org/~willkg/blog/dev/using_localstack_for_s3.html
  # More examples at https://medium.com/@andyalky/developing-aws-apps-locally-with-localstack-7f3d64663ce4
  localstack-s3:
    container_name: localstack-s3
    image: localstack/localstack
    env_file:
      - ./.env.testing
    ports:
      - '5000:5000'
      - '8080:8080'
    restart: on-failure
